import org.codehaus.groovy.grails.commons.ConfigurationHolder
import grails.util.*

environments {
    production {
        dataSource {
            //IMPORTANT: Change to "none" for a real production database with the
            //tables already existing
            dbCreate = "update"
            username = "sa"
            password = ""
            driverClassName = "org.h2.Driver"
            url = "jdbc:h2:file:mktplProdDb"
            pooled = true
            properties {
                minEvictableIdleTimeMillis = 180000
                timeBetweenEvictionRunsMillis = 180000
                testOnBorrow = true
                testWhileIdle = false
                testOnReturn = false
                validationQuery = "SELECT 1"
                validationInterval = 30000
                maxActive = 100
                initialSize = 10
                maxIdle = 50
                minIdle = 10
                removeAbandoned = false
                jdbcInterceptors = null
            }
        }

        elasticSearch {
            datastoreImpl = 'hibernateDatastore'
            client.mode = 'local'
            index.store.type = 'memory'
            path.data = "${System.properties['catalina.home']}/temp/data"

            //Note: We do our own custom indexing in Bootstrap.groovy. If this is overridden
            //search indexing will not behave as expected - specifically all listings will be
            //indexed on app startup, rather than just approved/enabled listings.
            bulkIndexOnStartup = false
        }

    }

}

// Variables used for CEF logging. These fields are combined to form the CEF prefix.
// For more information about CEF logging, check ArcSight documentation
cef {
    device {
        // The device vendor or organization
        vendor = "OZONE"
        // The device product name
        product = "Store"
        version = "500-27_L2::1.3"
    }
    // The CEF version
    version = 0

    enabled = true

    //set true to log database reads as well as modifications
    //WARNING - creates an enormous amount of logs
    verbose = false

    securityLevel = null
}

//local file path where uploaded images are stored.  The server process must have write access
//to this location, including the ability to create subdirectories
marketplace.imageStoragePath = "${System.properties['catalina.home']}/images"

//set to another URI to have the client retrieve images from there.
marketplace.imageUriBaseOverride = null

//The base URI that clients use to access this marketplace.
//This will likely need to be set when using a load balancer in order for
//URIs generated by the application to point to the balancer and not
//the app server.  When this parameter is null the base uri is
//determined from the characteristics of each HTTP request
marketplace.publicURI = null

//set to a list of mediatypes that are allowed to be stored as images, mapped to the
//file extension under which they should be stored.  Note: types that
//do not start with `image/` will not work regardless of this setting
marketplace.acceptableImageTypes = [
    'image/png': 'png',
    'image/jpeg': 'jpg',
    //'image/gif': 'gif',
    'image/webp': 'webp',
    'image/svg+xml': 'svg'
]

println "MarketplaceConfig.groovy completed successfully."
